### PR TITLE
Improve readability of underscore k in Spryker logo

### PR DESCRIPTION
**Pull request by b-boehne**
### Description

The underscore k irked me for quite a bit and I wanted to improve the readability. Not much more to it.  
Merge if you agree, decline if you don't :)

#### Change log

- improved readability of underscore k in Spryker logo

### Checklist
- [X] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Comment by darius-telycenas** [comment]
Why not picking something from https://textkool.com/en/test-ascii-art-generator?text=Spryker%20SDK — there are many more interesting ascii-fonts, like (random example):
```
 _____             _              _____ ____  _____ 
|   __|___ ___ _ _| |_ ___ ___   |   __|    \|  |  |
|__   | . |  _| | | '_| -_|  _|  |__   |  |  |    -|
|_____|  _|_| |_  |_,_|___|_|    |_____|____/|__|__|
      |_|     |___|                                 
```
vs existing:
```
┌────┐           ┌─┐            ┌────┬────┬─┬─┐
│ ───┼───┬─┬─┬─┬─┤ ├─┬───┬─┬─┐  │ ───┼─┐ ┐│ ┌─┘
├─── │ ┼ │ ┌─┤ │ │───┤ ┼─┤ ┌─┘  ├─── ├─┴─┘│ └─┐
└────┤  ┌┴─┘ ├─┐ ├─┴─┴───┴─┘    └────┴────┴─┴─┘
     └──┘    └───┘
```

**Comment by b-boehne** [comment]
> Why not picking something from https://textkool.com/en/test-ascii-art-generator?text=Spryker%20SDK — there are many more interesting ascii-fonts

Didn't want to change the existing feel of the logo.  
[sprymiker](https://github.com/sprymiker) put it up there for a reason and I don't want to mess with his work too much.

**Comment by alexanderM91** [comment]
Hey @b-boehne, looks awesome, but unfortunately we need to rename it from `Spryker SDK` to `Docker SDK`.
And of course If it's possible and you have some spare time you can propose an amazing options? 
Thank you.

**Comment by b-boehne** [comment]
Hi @alexanderM91, the new commit proposes a new font using the name.
I assume the filenames will be changed in a future refactoring or should I try and refactor this now?

**Comment by alexanderM91** [comment]
Several possible logos - https://github.com/spryker/docker-sdk/pull/345/files

cc: @fscholzspryker

**Comment by fscholzspryker** [comment]
From what is visible in github i think the first and second (bin/standalone/logo/colossal/spryker-cli.sh) is most readable. What do you think @b-boehne  ?

**Comment by b-boehne** [comment]
I don't even know @fscholzspryker 🙈, I'm not an authority on ASCII art, nor is this important by any means.
I just wanted to remove those 2 dashes on the `k` like in my first commit because they bothered me 😩

**Comment by fscholzspryker** [comment]
oh sry, after reading again I think @darius-telycenas wished for another "font" - so what do you think?

**Comment by b-boehne** [comment]
3rd and 4th are actually my favourite
but by any means, pick the one that you like

**Pull request closed without merging**
