### PR TITLE
 SC-3085: MariaDB v10.2-4 is supported

### PR DESCRIPTION
**Pull request by zyuzka**
- Ticket: https://spryker.atlassian.net/browse/SC-3085
- RG: https://release.spryker.com/release-groups/view/2695

-----------------------------

### Improvements

- Introduced support for `MariaDB` versions: 10.2, 10.3, and 10.4.

### CODE REVIEW

**Comment by alexanderM91** [comment]
Hi, @zyuzka , please prepare a release group with the release notes

**Comment by alexanderM91** [comment]
Also, during the epic requirements, we have to support these versions: 10.1, 10.2, 10.3, 10.4.

**Comment by zyuzka** [comment]
> Also, during the epic requirements, we have to support these versions: 10.1, 10.2, 10.3, 10.4.

Dmitry Mihailov should change requirements. MariaDB 10.1 have BC

**Comment by alexanderM91** [comment]
> > Also, during the epic requirements, we have to support these versions: 10.1, 10.2, 10.3, 10.4.
> 
> Dmitry Mihailov should change requirements. MariaDB 10.1 have BC

Thank you for your clarification.

**Pull request merged**
