### PR TITLE
SC-10057: New DockerSDK and DockerCLI logo

### PR DESCRIPTION
**Pull request by zyuzka**
### Description

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-10057

#### Change log

- updated logos for SDK and CLI

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Review by alexanderM91 — APPROVED** [review]

**Comment by darkopoposki** [comment]
A question regarding the new logo - is the typo in it on purpose?

**Comment by alexanderM91** [comment]
Hi @darkopoposki, 
"Spryker" has been replaced with "Docker", "SDK" remains unchanged.

**Comment by darkopoposki** [comment]
> Hi @darkopoposki, "Spryker" has been replaced with "Docker", "SDK" remains unchanged.

Hi @alexanderM91, thanks for you reply. I was referring to the typo in the word Docker of the logo (the commit is written Doker without a C) and was wondering if this is on purpose or a mistake.

**Comment by alexanderM91** [comment]
Ohh, yes, you are absolutely right. It was a typo. The fix already in the master. 
Thanks a lot for your attentiveness.

**Pull request merged**
