### PR TITLE
#Issue-367: Set SPRYKER_DEBUG_PROPEL_ENABLED depending if docker debug is set

### PR DESCRIPTION
**Pull request by dblaichinger**
### Description

- Ticket/Issue: https://github.com/spryker/docker-sdk/issues/367

#### Change log

- Set `SPRYKER_DEBUG_PROPEL_ENABLED` environment variable depending if docker debug is set

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Comment by alexanderM91** [comment]
Hey @dblaichinger,
thanks a lot for you contribution.

I have a small questions, why we cannot reuse `SPRYKER_DEBUG_ENABLED` environment variable in the Spryker configuration as a newly introduced environment variable holds the same value and based on the same configuration?

`
config[PropelConstants::PROPEL_DEBUG] = (bool)getenv('SPRYKER_DEBUG_ENABLED');
`

**Comment by dblaichinger** [comment]
Hey @alexanderM91,

thanks for your answer!

The only reason I've used a seperate env variable, because it also finds usage in the Spryker demo shops:
* https://github.com/spryker-shop/b2c-demo-shop/blob/master/config/Shared/config_default-docker.dev.php#L50
* https://github.com/spryker-shop/b2b-demo-shop/blob/master/config/Shared/config_default-docker.dev.php#L50

I'm fine with using just `SPRYKER_DEBUG_ENABLED` but maybe there is a reason having a separate flag for Propel debugging? Otherwise the demo shop configs might receive an update and use `SPRYKER_DEBUG_ENABLED` only?

**Comment by alexanderM91** [comment]
Hey @dblaichinger,

> maybe there is a reason having a separate flag for Propel debugging?

I am planning to investigate it more precisely but I don't see any reasons to use additional environment variable which is not configurable and contains the same value as `SPRYKER_DEBUG_ENABLED`.


> Otherwise the demo shop configs might receive an update and use SPRYKER_DEBUG_ENABLED only?
Yes, you are absolutely right. Most probably it will come with the next public release.

**Comment by dblaichinger** [comment]
Hi @alexanderM91,

sorry but can you please explain why this has been closed? 
The default config still uses env var `SPRYKER_DEBUG_PROPEL_ENABLED`:

> $config[PropelConstants::PROPEL_DEBUG] = (bool)getenv('SPRYKER_DEBUG_PROPEL_ENABLED');

https://github.com/spryker-shop/b2c-demo-shop/blob/master/config/Shared/config_default-docker.dev.php#L52

Or should there be an issue created at `spryker-shop/b2c-demo-shop`?

Thank you!

**Pull request closed without merging**
