### PR TITLE
[SC-8903] Add supervisorctl config

### PR DESCRIPTION
**Pull request by namikk**
### Ticket

- https://spryker.atlassian.net/browse/SC-8903

### Description

It is currently not possible to execute `supervisorctl` commands in containers built with docker-sdk. This PR updates the `context/php/debug/supervisord.conf` file in order to enable access to `supervisorctl` from inside the containers.

Our current use case for this change is fast toggling of xdebug without restarting the containers. The current way to do this with docker-sdk is too slow (it restarts all containers), so we created a custom script which can toggle xdebug without restarting all containers. For that to work we need the `supervisorctl` command to be available in the containers.

#### Change log

- added `[unix_http_server]`, `[rpcinterface:supervisor]` and `[supervisorctl]` sections to `context/php/debug/supervisord.conf`

### Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Comment by namikk** [comment]
Hello @alexanderM91 is there an official way to request a code review? Do I need to add any labels or anything? Or is it enough to just tag and ask like I did just now?

**Comment by alexanderM91** [comment]
Hey @namikk, thanks a lot for contribution and sorry for the long response time.
As for me it looks 👍, we will schedule it in our QA queue.

**Review by alexanderM91 — APPROVED** [review]

**Comment by namikk** [comment]
Hey @alexanderM91 , no worries, I know you guys are super busy. And thanks for the update 👍

**Comment by FranQy** [comment]
Hello @alexanderM91, 
I've found this feature really helpful. Could you merge it please?
I see that you already approved it and it will be great to be able to toggle xdebug without restarting all containers.

**Comment by namikk** [comment]
FYI I just pulled latest docker-sdk, PR is now up to date.

**Comment by alexanderM91** [comment]
Hi, thanks a lot, the current feature in the QA plan.
We will start it after M1.

**Pull request merged**
